### ISSUE TITLE
Bug: input paths with dots

### ISSUE THREAD

**Issue by mliulion** [up2code/yaml2props#2]
This line... https://github.com/up2code/yaml2props/blob/20f33898c36818aeea2c25c6181e2d65b22bbce3/yaml2props.py#L75 
causes an unexpected behavior when the input filepath has dots, for example:
```
/home/foo/bar.d/moo.oo/fuuu/my_file.yaml
```
It writes a `/home/foo/bar.properties` file instead of a `/home/foo/bar.d/moo.oo/fuuu/my_file.properties` file

I guess that is better using libraries that deals with file paths instead of regular expressions 

Also it could be much better to append the `.properties` extension. In my example it would be `my_file.yaml.properties`

**Comment by up2code** [comment]
Fixed and I had add option for let user specific output path by themself
<img width="762" alt="Screen Shot 2564-01-14 at 16 01 53" src="https://user-images.githubusercontent.com/2321626/104567947-fa987f00-5681-11eb-9e3a-551cd2943761.png">
